project_id = "sdxrlczdzcpqwppytzuv"

[functions.process-document]
verify_jwt = true

[functions.chat-document]
verify_jwt = true

[functions.delete-document]
verify_jwt = true

[functions.chat-session]
verify_jwt = true

[functions.register-document]
verify_jwt = true

[functions.health-check]
verify_jwt = false
